#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd at denx.de.
#
# (C) Copyright 2001
# Erik Theisen, Wave 7 Optics, etheisen at mindspring.com.
#
# SPDX-License-Identifier:      GPL-2.0+
#

#ccflags-y += -DDEBUG

obj-$(CONFIG_PWM_IMX) += pwm-imx.o
